import ItemCard from "@/components/itemCard/ItemCard";
import HomeWorkIcon from "@mui/icons-material/HomeWork";
import RamenDiningIcon from "@mui/icons-material/RamenDining";
import { Box, Typography } from "@mui/material";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Fast Foodie POS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography
        sx={{
          fontSize: "30px",
          py: 3,
          display: "flex",
          justifyContent: "center",
          mx: "auto",
        }}
      >
        Food Order App
      </Typography>

      <Box sx={{ display: "flex", justifyContent: "center" }}>
        <ItemCard
          href={"/backoffice"}
          icon={<HomeWorkIcon />}
          title={"Back Office App"}
        />
        <ItemCard
          href={"/order"}
          icon={<RamenDiningIcon />}
          title={"Order App"}
        />
      </Box>
    </>
  );
};

export default Home;
